site_name: SedonaDB
site_description: "Documentation for Apache SedonaDB"
nav:
   - Home: index.md
   - SedonaDB Guides:
     - CLI Quickstart: quickstart-cli.md
     - Python Quickstart: quickstart-python.ipynb
     - Development: development.md
   - SedonaDB Reference:
      - Python:
          - Python Functions: reference/python.md
      - SQL:
          - SQL Functions: reference/sql.md
          - Spatial Joins: reference/sql-joins.md
          - Read Parquet Files: reference/read-parquet-files.md
   - Blog: "https://sedona.apache.org/latest/blog/"
   - Apache Software Foundation: "https://sedona.apache.org/latest/asf/asf/"
   - Return to Sedona Homepage: "https://sedona.apache.org/latest/"
repo_url: https://github.com/apache/sedona-db
repo_name: apache/sedona-db
theme:
  name: material
  font:
    font: false
    name: 'material'
  palette:
    primary: custom
    accent: 'green'
  favicon: image/sedona_logo_symbol.png
  logo: image/sedona_logo_symbol_white.svg
  icon:
    logo: fontawesome/solid/earth-americas
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.share
    - search.suggest
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
extra:
  version:
    provider: mike
    default:
       - 0.1


extra_css:
  - stylesheets/extra.css

copyright: Copyright © 2025 The Apache Software Foundation. Apache Sedona, Sedona, Apache, the Apache feather logo, and the Apache Sedona project logo are either registered trademarks or trademarks of The Apache Software Foundation in the United States and other countries. All other marks mentioned may be trademarks or registered trademarks of their respective owners. Please visit <a href="https://www.apache.org/">Apache Software Foundation</a> for more details.<img referrerpolicy="no-referrer-when-downgrade" src="https://static.scarf.sh/a.png?x-pxid=f3e121f6-c909-4592-8be6-5bd345768cba" /><img referrerpolicy="no-referrer-when-downgrade" src="https://analytics.apache.org/matomo.php?idsite=74&rec=1" />

exclude_docs: |
     snippets/*
     README.md
markdown_extensions:
   - admonition
   - attr_list
   - codehilite
   - footnotes
   - toc:
        permalink: true
        toc_depth: 3
   - pymdownx.arithmatex
   - pymdownx.betterem:
        smart_enable: all
   - pymdownx.caret
   - pymdownx.critic
   - pymdownx.details
   - pymdownx.emoji
   - pymdownx.highlight
   - pymdownx.inlinehilite
   - pymdownx.magiclink
   - pymdownx.mark
   - pymdownx.smartsymbols
   - pymdownx.snippets:
        base_path: ["docs/"]
   - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
   - pymdownx.tabbed:
        alternate_style: true
   - pymdownx.tasklist:
        custom_checkbox: true
   - pymdownx.tilde
plugins:
   - search
   - macros
   - git-revision-date-localized:
        type: datetime
   - mkdocs-jupyter
   - mike:
        version_selector: false
   - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
          - custom-skip-class-name
          - skip-lightbox
        auto_caption: false
        caption_position: bottom
        background: white
        shadow: false
        manual: false
   - tags
   - mkdocstrings:
          handlers:
               python:
          # 'inventories' is a direct setting for the Python handler
                    inventories:
                         - https://docs.python.org/3/objects.inv
                         - https://geopandas.org/en/stable/objects.inv
                         - https://pandas.pydata.org/docs/objects.inv
     # All display and path options go under a SINGLE 'options' block
                    options:
                         docstring_section_style: list
                         docstring_style: google
                         line_length: 80
                         separate_signature: true
                         show_root_heading: true
                         show_signature_annotations: true
                         show_source: false
                         show_symbol_type_toc: true
                         signature_crossrefs: true
                         extra:
                              paths: ['python']
