name: Lint and Test

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: pip install -r requirements.txt

      # The pre-commit/action is replaced with this manual command
      - name: Run pre-commit checks
        run: pre-commit run --all-files
